version: "3"

services: 
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8090:8090"
        env_file:
            - './config/influxdb/influxdb.env'
        volumes:
            # Data persistency
            - ./docker/influxdb:/var/lib/influxdb

    telegraf:
        image: telegraf:latest
        container_name: telegraf
        links:
            - influxdb
        volumes:
            - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro


    # Define a Chronograf service
    chronograf:
        image: chronograf:1.3.8
        ports:
            - "8888:8888"
        links:
            - influxdb